// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioscoAPI.Models;

public partial class Articulo
{
    public int IdArticulo { get; set; }

    public string Nombre { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public int IdCategoria { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Categoria IdCategoriaNavigation { get; set; }
}