// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioscoAPI.Models;

public partial class DetalleFactura
{
    public int IdDetalle { get; set; }

    public int IdFactura { get; set; }

    public int IdArticulo { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Articulo IdArticuloNavigation { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }
}